version: "3.8"

services:
  db:
    container_name: mongo-database
    image: mongo
    restart: unless-stopped
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_ROOT_USERNAME}"
    #   MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_ROOT_PASSWORD}"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

volumes:
  mongodb_data:

networks:
  default:
